server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/client
    driverClassName: com.mysql.cj.jdbc.Driver
    password: mysql
    username: root
  flyway:
    out-of-order: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate