server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/client
    driverClassName: org.postgresql.Driver
    password: postgres
    username: postgres
  flyway:
    out-of-order: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      org:
        hibernate:
          envers:
            store_data_at_delete: true